.TH "TAP1Proyect.cpp" 3 "Version 0.1" "TAP1Proyect" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TAP1Proyect.cpp
.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBExamen\fP ()"
.br
.ti -1c
.RI "void \fBMenu\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void Examen ()"

.SS "int main ()"

.SS "void Menu ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for TAP1Proyect from the source code\&.
